trigger:
- release

pool:
  name: 'Linux'

steps:
- task: UseDotNet@2
  displayName: 'get sdk'
  inputs:
    packageType: 'sdk'
    version: '7.x'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      cd $(Build.SourcesDirectory)
      chmod +x ./build.sh
      ./build.sh Compile
  displayName: 'Run Nuke build'